server:
  port: 8081

spring:
  application:
    name: ARTICLE-SERVICE
  profiles:
    active: dev
  datasource:
    url: "jdbc:mysql://db-linux-msa-board.cr60oge6q5of.ap-northeast-2.rds.amazonaws.com:3306/linux-msa-board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true"
    username: admin
    password: password1616
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update       # 테이블이 없으면 생성, 있으면 업데이트
    show-sql: true           # SQL 콘솔 출력
    properties:
      hibernate:
        format_sql: true     # SQL 출력 포멧
        dialect: org.hibernate.dialect.MySQL8Dialect


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    com.example.article_service: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

